name: cellprofiler
channels:
  - anaconda
  - conda-forge
dependencies:
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - pillow
  - pip
  - python=2
  - mysql-python
  - numpy==1.13.0
  - tifffile
  - vigra
  - pip:
    - git+https://github.com/CellProfiler/CellProfiler.git@v2.3.0#egg=CellProfiler
