name: cellprofiler
channels:
  - anaconda
  - conda-forge
dependencies:
  - h5py<=2.7.0
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - pillow
  - pip
  - python=2
  - pyzmq=15.3.0
  - matplotlib!=2.1.0,>=2.0.0
  - mysql-python
  - numpy<=1.13.0
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - tifffile
  - vigra
  - pip:
    - cellh5
    - centrosome>=1.0.4
    - inflect
    - prokaryote==2.3.2
    - javabridge==1.0.15
    - python-bioformats==1.3.1
    - git+https://github.com/CellProfiler/CellProfiler.git@v2.2.2#egg=CellProfiler
